apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ml-pipeline
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: ml-pipeline
    template:
      ref: ml-pipeline
