apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: ml-pipeline
  name: el-ml-pipeline
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-ml-pipeline
    weight: 100